services:
  app:
    image: your-dockerhub-username/tyreplus-app:latest
    ports:
      - "80:8080" # Map public port 80 to internal 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DB_PASSWORD=${PROD_DB_PASSWORD}
      - JWT_SECRET=${PROD_JWT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - tyreplus-net

  postgres:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
      - POSTGRES_DB=tyreplus_dealer_db
    networks:
      - tyreplus-net

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - tyreplus-net

networks:
  tyreplus-net:
volumes:
  pgdata: